name: 기능 추가
description: 새로운 기능이나 사양이 있나요?
title: '[feat] '
projects: ["resistance2/1"]
labels: ['feat']
body:
  - type: textarea
    id: feat-description
    attributes:
      label: 📄 설명
      description: 새로운 기능을 설명해주세요.
      placeholder: 자세한 설명을 제공해주세요!
    validations:
      required: true
